# The server to fetch assets from
# Current available options are US and CN
server = "CN"

# The path to cache resource versions at
versions_path = "cache/versions.json"

# The path to cache asset hashes at
hashes_path = "cache/hashes.json"

# If set to false, the files at versions_path and hashes_path will not be updated
update_cache = true

# The output directory for extracted assets
output_dir = "assets"

# Optional; an asset will only be processed if its path contains one of the paths in this list
path_whitelist = [
    "avg/characters/",
    "avg/bg/",
    "spritepack/ui_roguelike_topic_item",
    "spritepack/ui_equip_big_img",
    "avg/items/",
    "spritepack/ui_char_avatar",
    "avg/imgs/",
    "spritepack/skill_icons",
    "spritepack/ui_item_icons",
    "ui/rglktopic/rogue_1.ab",
    "raw/video/"
]
