name: Test Dependency Install Only

on:
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Create requirements file
        run: |
          echo "torch==1.12.1" >> requirements_avatars.txt
          echo "torchvision==0.13.1" >> requirements_avatars.txt
          echo "imagesize==1.4.1" >> requirements_avatars.txt
          echo "openmim==0.3.2" >> requirements_avatars.txt
          echo "mmcv-full==1.6.2" >> requirements_avatars.txt
          echo "mmdet==2.25.2" >> requirements_avatars.txt
          echo "mmpose==0.28.1" >> requirements_avatars.txt
          echo "anime-face-detector==0.0.9" >> requirements_avatars.txt
          echo "numpy==1.23.3" >> requirements_avatars.txt
          echo "opencv-python-headless==4.11.0.86" >> requirements_avatars.txt

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies without build isolation
        run: pip install --no-build-isolation -r requirements_avatars.txt

      - name: Show installed packages
        run: pip freeze
