name: Test Dependency Installation

on:
  workflow_dispatch:

jobs:
  test-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          pip install torch==1.12.1
          pip install torchvision==0.13.1
          pip install imagesize==1.4.1
          pip install numpy==1.23.3
          pip install openmim==0.3.2
          python -m mim install mmcv-full==1.6.2
          python -m mim install mmdet==2.25.2
          pip install wheel
          python -m mim install mmpose==0.28.1
          pip install anime-face-detector==0.0.9
          pip freeze
          

      - name: Verify import
        run: python -c "import numpy, imagesize, cv2, anime_face_detector"
